export const SHIRT_LIST_REQUEST = 'SHIRT_LIST_REQUEST';
export const SHIRT_LIST_SUCCESS = 'SHIRT_LIST_SUCCESS';
export const SHIRT_LIST_FAIL = 'SHIRT_LIST_FAIL';

export const SHIRT_DETAILS_REQUEST = 'SHIRT_DETAILS_REQUEST';
export const SHIRT_DETAILS_SUCCESS = 'SHIRT_DETAILS_SUCCESS';
export const SHIRT_DETAILS_FAIL = 'SHIRT_DETAILS_FAIL';

