const data={
    shirts:[
        {
            _id : '1',
            name: 'Blue slim fit',
            category: 'Shirts',
            image: '/images/s1.jpg',
            price: 995,
            brand: 'Denim',
            rating: 3.5,
            numReviews: 21,
            countInStock: 5,
            descriptn: 'Sure to reserve a spot in your core wardrobe, this Mens sky blue slim fit shirt from our Miami collection is crafted from 100% cotton. This printed shirt is elevated by the button-down collar and chest pocket with brand embroidery.',
        },
        {
            _id : '2',
            name: 'Pine Regular fit',
            category: 'Shirts',
            image: '/images/s2.jpg',
            price: 1890,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 25,
            countInStock: 5,
            descriptn: 'Sure to reserve a spot in your core wardrobe, this Mens Pine regular slim fit shirt from our Miami collection is crafted from 100% cotton. This printed shirt is elevated by the button-down collar and chest pocket with brand embroidery.',
        },
        {
            _id : '3',
            name: 'Striped slim fit',
            category: 'Shirts',
            image: '/images/s3.jpg',
            price: 1090,
            brand: 'Roadster',
            rating: 3,
            numReviews: 7,
            countInStock: 5,
            descriptn: 'Sure to reserve a spot in your core wardrobe, this Mens striped slim fit shirt from our Miami collection is crafted from 100% cotton. This printed shirt is elevated by the button-down collar and chest pocket with brand embroidery.',
        },
        {
            _id : '4',
            name: 'Green Checked',
            category: 'Shirts',
            image: '/images/s4.jpg',
            price: 950,
            brand: 'Roadster',
            rating: 4,
            numReviews: 13,
            countInStock: 5,
            descriptn: 'Sure to reserve a spot in your core wardrobe, this Mens green-checked fit shirt from our Miami collection is crafted from 100% cotton. This printed shirt is elevated by the button-down collar and chest pocket with brand embroidery.',
        },
        {
            _id : '5',
            name: 'Black Solid fit',
            category: 'Shirts',
            image: '/images/s5.jpg',
            price: 1600,
            brand: 'Nike',
            rating: 5,
            numReviews: 17,
            countInStock: 0,
            descriptn: 'Sure to reserve a spot in your core wardrobe, this Mens sky black solid fit shirt from our Miami collection is crafted from 100% cotton. This printed shirt is elevated by the button-down collar and chest pocket with brand embroidery.',
        },
        {
            _id : '6',
            name: 'Pink slim fit',
            category: 'Shirts',
            image: '/images/s6.jpg',
            price: 1640,
            brand: 'Roadster',
            rating: 4.5,
            nuRreviews: 11,
            countInStock: 5,
            descriptn: 'Sure to reserve a spot in your core wardrobe, this Mens pink slim fit shirt from our Miami collection is crafted from 100% cotton. This printed shirt is elevated by the button-down collar and chest pocket with brand embroidery.',
        },
        {
            _id : '7',
            name: 'Navy Checked',
            category: 'Shirts',
            image: '/images/s7.jpg',
            price: 1015,
            brand: 'Denim',
            rating: 4,
            numReviews: 16,
            countInStock: 0,
            descriptn: 'Sure to reserve a spot in your core wardrobe, this Mens sky Navy-checked slim fit shirt from our Miami collection is crafted from 100% cotton. This printed shirt is elevated by the button-down collar and chest pocket with brand embroidery.',
        },
        {
            _id : '8',
            name: 'White Checked',
            category: 'Shirts',
            image: '/images/s8.jpg',
            price: 915,
            brand: 'Roadster',
            rating: 4,
            numReviews: 16,
            countInStock: 0,
            descriptn: 'Sure to reserve a spot in your core wardrobe, this Mens White-checked slim fit shirt from our Miami collection is crafted from 100% cotton. This printed shirt is elevated by the button-down collar and chest pocket with brand embroidery.',
        },
        {
            _id : '9',
            name: 'Black Slim Fit',
            category: 'Shirts',
            image: '/images/s9.jpg',
            price: 1215,
            brand: '',
            rating: 4.6,
            numReviews: 16,
            countInStock: 4,
            descriptn: 'Sure to reserve a spot in your core wardrobe, this Mens Black slim fit shirt from our Miami collection is crafted from 100% cotton. This printed shirt is elevated by the button-down collar and chest pocket with brand embroidery.',
        }
    ],
    shoes:[
        {
            _id : '1',
            name: 'Adidas Originals',
            category: 'Shoes',
            image: '/images/sh1.jpg',
            price: 2995,
            brand: 'Adidas',
            rating: 4.5,
            numReviews: 71,
            countInStock: 53,
            descriptn: 'Great everyday trainer for modern runner to go that extra mile. They have a mesh upper accented by contrast 3-Stripes. The IMEVA midsole and Rubber outsole provide comfort and support to their every step.',
        },
        {
            _id : '2',
            name: 'Nike AirMax',
            category: 'Shoes',
            image: '/images/sh2.jpg',
            price: 1890,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 25,
            countInStock: 5,
            descriptn: 'Great everyday trainer for modern runner to go that extra mile. They have a mesh upper accented by contrast 3-Stripes. The IMEVA midsole and Rubber outsole provide comfort and support to their every step.',
        },
        {
            _id : '3',
            name: 'Nike AirForce',
            category: 'Shoes',
            image: '/images/sh3.jpg',
            price: 1090,
            brand: 'Nike',
            rating: 3.8,
            numReviews: 7,
            countInStock: 5,
            descriptn: 'Great everyday trainer for modern runner to go that extra mile. They have a mesh upper accented by contrast 3-Stripes. The IMEVA midsole and Rubber outsole provide comfort and support to their every step.',
        },
        {
            _id : '4',
            name: 'Adidas Originals',
            category: 'Shoes',
            image: '/images/sh4.jpg',
            price: 3950,
            brand: 'Adidas',
            rating: 5,
            numReviews: 113,
            countInStock: 5,
            descriptn: 'Great everyday trainer for modern runner to go that extra mile. They have a mesh upper accented by contrast 3-Stripes. The IMEVA midsole and Rubber outsole provide comfort and support to their every step.',
        },
        {
            _id : '5',
            name: 'Nike Joyride',
            category: 'Shoes',
            image: '/images/sh5.jpg',
            price: 1600,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 17,
            countInStock: 0,
            descriptn: 'Great everyday trainer for modern runner to go that extra mile. They have a mesh upper accented by contrast 3-Stripes. The IMEVA midsole and Rubber outsole provide comfort and support to their every step.',
        },
        {
            _id : '6',
            name: 'Adidas Originals',
            category: 'Shoes',
            image: '/images/sh6.jpg',
            price: 3640,
            brand: 'Nike',
            rating: 4.5,
            nuRreviews: 91,
            countInStock: 5,
            descriptn: 'Great everyday trainer for modern runner to go that extra mile. They have a mesh upper accented by contrast 3-Stripes. The IMEVA midsole and Rubber outsole provide comfort and support to their every step.',
        },
        {
            _id : '7',
            name: 'Sparx Flexible',
            category: 'Shoes',
            image: '/images/sh7.jpg',
            price: 1915,
            brand: 'Sparx',
            rating: 4,
            numReviews: 16,
            countInStock: 3,
            descriptn: 'Great everyday trainer for modern runner to go that extra mile. They have a mesh upper accented by contrast 3-Stripes. The IMEVA midsole and Rubber outsole provide comfort and support to their every step.',
        },
        {
            _id : '8',
            name: 'Adidas Originals',
            category: 'Shoes',
            image: '/images/sh8.jpg',
            price: 3015,
            brand: 'Adidas',
            rating: 4,
            numReviews: 16,
            countInStock: 0,
            descriptn: 'Great everyday trainer for modern runner to go that extra mile. They have a mesh upper accented by contrast 3-Stripes. The IMEVA midsole and Rubber outsole provide comfort and support to their every step.',
        }
    ]
}
export default data;